apiVersion: v1
kind: Service
metadata:
  name: osrm-car
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: osrm-car
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-car
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: osrm-car
        track: stable
    spec:     
      containers:
      - name: osrm-backend-k8s
        image: .../osrm-backend-k8s:latest
        env:
        - name: OSRM_MODE
          value: RESTORE       
        - name: OSRM_DATA_LABEL
          value: hamburg-car-20200126        
        - name: OSRM_AWS_ACCESS_KEY_ID
          value: ...
        - name: OSRM_AWS_SECRET_ACCESS_KEY
          value: ...
        - name: OSRM_AWS_DEFAULT_REGION
          value: eu-central-1
        - name: OSRM_AWS_S3_BUCKET
          value: s3://...  
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /nearest/v1/healthz/0,0
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1
